baseURL = 'https://www.clipcrow.com/'
languageCode = 'ja'
title = 'ClipCrow LLC'
relativeurls = true
contentDir = "content"
disableKinds = ["RSS", "sitemap", 'term', 'taxonomy']
ignoreErrors = ["error-disable-taxonomy"]
paginate = 5

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true
